/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventoryproject;

import com.inventorysystem.helpers.DBConnection;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author HP
 */
public class BillReport extends javax.swing.JInternalFrame {
    Connection con;
    PreparedStatement pst;
    List<CustomerClass> billList;

    /**
     * Creates new form BillReport
     */
    public BillReport() {
        initComponents();
        billList = new ArrayList<>();
        populateBillDateCombo();
    }
    
  
    
         
    
    public ArrayList<BillClass> getBillList()
    {
        ArrayList<BillClass> billList=new ArrayList<BillClass>();
        
        try
        {
            String customername=txtcustomername.getText();
            //String selectedName = (String) combocustomername.getSelectedItem();
            //Class.forName("com.mysql.jdbc.Driver");
            con=DBConnection.getConnection();
            PreparedStatement pstmt = con.prepareStatement("select B.id, C.first_name, bill, status, pending, date from bill B, customer C where B.customer_id=C.id and C.first_name=?");
            pstmt.setString(1, customername);
            //pst.setInt(1, Integer.parseInt(billList.get(combocustomername.getSelectedIndex()-1).getId()));
            ResultSet rs = pstmt.executeQuery();
            
            //
            BillClass bill;
            while(rs.next())
            {
            bill=new BillClass(rs.getString("B.id"), rs.getString("C.first_name"), rs.getString("bill"), rs.getString("status"), rs.getString("pending"), rs.getString("date"));
            billList.add(bill);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return billList;
    }
    
    public void showData()
    {
        ArrayList<BillClass> list= getBillList();
        DefaultTableModel model=getModel();
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getBillid();
            row[1]=list.get(i).getCustomername();
            row[2]=list.get(i).getAmount();
            row[3]=list.get(i).getStatus();
            row[4]=list.get(i).getPendingpayment();
            row[5]=list.get(i).getDate();
            
            model.addRow(row);
        }
        jTable1.setModel(model);
    }
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        combodate = new javax.swing.JComboBox();
        radiocash = new javax.swing.JRadioButton();
        radiocredit = new javax.swing.JRadioButton();
        btnview = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtcustomername = new javax.swing.JTextField();
        txtbillid = new javax.swing.JTextField();

        setClosable(true);
        setMaximizable(true);
        setTitle("Bill Report");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Bill ID", "Customer Name", "Total Bill", "Status", "Pending Payment", "Date"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Search by Customer");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Search by Bill ID");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Search by Date");

        combodate.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                combodateItemStateChanged(evt);
            }
        });

        buttonGroup1.add(radiocash);
        radiocash.setSelected(true);
        radiocash.setText("Cash");
        radiocash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocashActionPerformed(evt);
            }
        });

        buttonGroup1.add(radiocredit);
        radiocredit.setText("Credit");
        radiocredit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radiocreditActionPerformed(evt);
            }
        });

        btnview.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnview.setText("Click Here");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("Search by Pending Payment");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setText("View Bill through PDF ");

        txtcustomername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcustomernameActionPerformed(evt);
            }
        });

        txtbillid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbillidActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(combodate, 0, 129, Short.MAX_VALUE)
                    .addComponent(txtcustomername)
                    .addComponent(txtbillid))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(radiocash)
                        .addGap(18, 18, 18)
                        .addComponent(radiocredit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnview, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(radiocash)
                    .addComponent(radiocredit)
                    .addComponent(jLabel5)
                    .addComponent(txtcustomername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtbillid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(combodate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnview)
                            .addComponent(jLabel4))
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    
    public ArrayList<BillClass> getBillList1()
    {
        ArrayList<BillClass> billList=new ArrayList<BillClass>();
        
        try
        {
            String billid = txtbillid.getText();
            //Class.forName("com.mysql.jdbc.Driver");
            con=DBConnection.getConnection();
            PreparedStatement pstmt = con.prepareStatement("select B.id, C.first_name, bill, status, pending, date from bill B, customer C where B.customer_id=C.id and B.id=?");
            pstmt.setString(1, billid);
            ResultSet rs = pstmt.executeQuery();
            
            //
            BillClass bill;
            while(rs.next())
            {
            bill=new BillClass(rs.getString("B.id"), rs.getString("C.first_name"),  rs.getString("bill"), rs.getString("status"), rs.getString("pending"), rs.getString("date"));
            billList.add(bill);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return billList;
    }
    
    public void showData1()
    {
        ArrayList<BillClass> list= getBillList1();
        DefaultTableModel model=getModel();
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getBillid();
            row[1]=list.get(i).getCustomername();
            row[2]=list.get(i).getAmount();
            row[3]=list.get(i).getStatus();
            row[4]=list.get(i).getPendingpayment();
            row[5]=list.get(i).getDate();
            
            model.addRow(row);
        }
        jTable1.setModel(model);
    }
    
    private void populateBillDateCombo() {
    try {
        con = DBConnection.getConnection();
        PreparedStatement pstmt = con.prepareStatement("select date from bill");
        
        ResultSet rs = pstmt.executeQuery();
        combodate.addItem("");
        while (rs.next())
            combodate.addItem(rs.getString("date"));
        
    } catch (SQLException ex) {
        Logger.getLogger(Customer.class.getName()).log(Level.SEVERE, null, ex);
    }
    }
    
    public ArrayList<BillClass> getBillList2()
    {
        ArrayList<BillClass> billList=new ArrayList<BillClass>();
        
        try
        {
            String selectedDate = (String) combodate.getSelectedItem();
            //Class.forName("com.mysql.jdbc.Driver");
            con=DBConnection.getConnection();
            PreparedStatement pstmt = con.prepareStatement("select B.id, C.first_name, bill, status, pending, date from bill B, customer C where B.customer_id=C.id and date=?");
            pstmt.setString(1, selectedDate);
            ResultSet rs = pstmt.executeQuery();
            
            //
            BillClass bill;
            while(rs.next())
            {
            bill=new BillClass(rs.getString("B.id"), rs.getString("C.first_name"), rs.getString("bill"), rs.getString("status"), rs.getString("pending"), rs.getString("date"));
            billList.add(bill);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return billList;
    }

    private DefaultTableModel getModel() {
        
        return(new DefaultTableModel(
            new Object [][] {
            },
            new String [] {
                "Bill ID", "Customer Name", "Total Bill", "Status", "Pending Payment", "Date"
            }
        ));
        
    }
    
    public void showData2()
    {
        ArrayList<BillClass> list= getBillList2();
        DefaultTableModel model=getModel();
        Object[] row=new Object[6];
        
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getBillid();
            row[1]=list.get(i).getCustomername();
            row[2]=list.get(i).getAmount();
            row[3]=list.get(i).getStatus();
            row[4]=list.get(i).getPendingpayment();
            row[5]=list.get(i).getDate();
            
            model.addRow(row);
        }        
        
        jTable1.setModel(model);
    }
    
    boolean isShown = false;
    
    private void combodateItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_combodateItemStateChanged
        if (!isShown)
            showData2();
        
        isShown = !isShown;
    }//GEN-LAST:event_combodateItemStateChanged

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnviewActionPerformed
    
    public ArrayList<BillClass> getBillList3()
    {
        ArrayList<BillClass> billList=new ArrayList<BillClass>();
        
        try
        {
            boolean status=radiocash.isSelected();
            //Class.forName("com.mysql.jdbc.Driver");
            con=DBConnection.getConnection();
            PreparedStatement pstmt = con.prepareStatement("select B.id, C.first_name, bill, status, pending, date from bill B, customer C where B.customer_id=C.id and status=?");
            pstmt.setBoolean(1, status);
            ResultSet rs = pstmt.executeQuery();
            
            //
            BillClass bill;
            while(rs.next())
            {
            bill=new BillClass(rs.getString("B.id"), rs.getString("C.first_name"), rs.getString("bill"), rs.getString("status"), rs.getString("pending"), rs.getString("date"));
            billList.add(bill);
            }
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        return billList;
    }
    
    public void showData3()
    {
        ArrayList<BillClass> list= getBillList3();
        DefaultTableModel model=getModel();
        Object[] row=new Object[6];
        for(int i=0;i<list.size();i++)
        {
            row[0]=list.get(i).getBillid();
            row[1]=list.get(i).getCustomername();
            row[2]=list.get(i).getAmount();
            row[3]=list.get(i).getStatus();
            row[4]=list.get(i).getPendingpayment();
            row[5]=list.get(i).getDate();
            
            model.addRow(row);
        }
        jTable1.setModel(model);
    }
   
    
    private void radiocashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocashActionPerformed
      showData3();
    }//GEN-LAST:event_radiocashActionPerformed

    private void radiocreditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radiocreditActionPerformed
       showData3();
    }//GEN-LAST:event_radiocreditActionPerformed

    private void txtcustomernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcustomernameActionPerformed
       showData();
    }//GEN-LAST:event_txtcustomernameActionPerformed

    private void txtbillidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbillidActionPerformed
       showData1();
    }//GEN-LAST:event_txtbillidActionPerformed
    
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnview;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox combodate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JRadioButton radiocash;
    private javax.swing.JRadioButton radiocredit;
    private javax.swing.JTextField txtbillid;
    private javax.swing.JTextField txtcustomername;
    // End of variables declaration//GEN-END:variables
}
